#!/usr/bin/python

import boto3
import sys
import os
import random

PRIORITY_MIN_POS = 1
PRIORITY_MAX_POS = 5000


def _priority():
    """
    Generate random priority within 1 and 5000
    :return: int
    """
    return random.randrange(PRIORITY_MIN_POS, PRIORITY_MAX_POS)


def main(listener_arn):
    client = boto3.client('elbv2')

    rules = client.describe_rules(
        ListenerArn=listener_arn,
    )['Rules']

    priorities = [rule['Priority'] for rule in rules if rule['Priority'].isdigit()]

    is_unique = False

    while not is_unique:
        priority = _priority()
        if priority not in priorities:
            return priority


if __name__ == '__main__':
    try:
        if len(sys.argv) < 2:
            raise Exception('usage "{} arn:aws:elasticloadbalancing:us-west-2:123456789123:listener/app/alb/xxxxxxxxxx/yyyyyyyyyyy"'.format(os.path.basename(__file__)))
        print main(sys.argv[1])
        exit(0)
    except Exception as e:
        print "Error: {}".format(str(e))
        exit(1)