{{/*
# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
*/}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "nist-data-mirror.fullname" . }}
  labels:
    {{- include "nist-data-mirror.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "nist-data-mirror.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nist-data-mirror.selectorLabels" . | nindent 8 }}
    spec:
{{- if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
{{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          {{- with .Values.env }}
{{- toYaml . | nindent 8 }}
          {{- end }}    
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
{{- if .Values.readinessProbe.enabled}}
        readinessProbe:
          httpGet:
            path: /
            port: http
{{ toYaml .Values.readinessProbe.settings | indent 10 }}
{{- end }}
{{- if .Values.livenessProbe.enabled}}
        livenessProbe:
          httpGet:
            path: /
            port: http
{{ toYaml .Values.livenessProbe.settings | indent 10 }}
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
          {{- with .Values.volumeMounts }}
{{- toYaml . | nindent 8 }}
          {{- end }}
        - name: nist-data
          mountPath: /usr/local/apache2/htdocs
          subPath: htdocs
      volumes:
        {{- with .Values.volumes }}
{{- toYaml . | nindent 8 }}
        {{- end }}
        - name: nist-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.data.existingClaim }}{{ .Values.persistence.data.existingClaim }}{{- else }}{{ template "nist-data-mirror.fullname" . }}-data{{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.dnsConfig }}
      dnsConfig:
{{ toYaml . | indent 8 }}
    {{- end }}


